-- Cofraternidad: esquema inicial para Supabase/PostgreSQL
-- Ejecutar completo en Supabase > SQL Editor.

create extension if not exists pgcrypto;

create type public.user_role as enum ('admin', 'church');
create type public.church_status as enum ('Solvente', 'En mora', 'En proceso');
create type public.payment_status as enum ('Pendiente', 'Aprobado', 'Rechazado');
create type public.legal_status as enum ('Recibido', 'En análisis', 'En Notaría/Registro', 'Concluido', 'Rechazado');

create table public.churches (
  id bigint generated by default as identity primary key,
  name text not null,
  pastor text not null default '',
  rif text unique,
  phone text default '',
  email text default '',
  city text default 'Venezuela',
  address text default '',
  members integer not null default 0 check (members >= 0),
  status public.church_status not null default 'Solvente',
  initials text not null default 'IG',
  color text not null default 'bg-emerald-100 text-emerald-800 border-emerald-200',
  foundation_year integer check (foundation_year between 1800 and 2200),
  last_payment_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  name text not null default '',
  role public.user_role not null default 'church',
  church_id bigint references public.churches(id) on delete set null,
  created_at timestamptz not null default now(),
  constraint church_users_need_church check (role = 'admin' or church_id is not null)
);

create table public.app_config (
  id boolean primary key default true check (id),
  bcv_rate numeric(12, 4) not null default 45.50 check (bcv_rate > 0),
  org_name text not null default 'Cofraternidad de Iglesias',
  legal_department text not null default 'Departamento Legal y Registro',
  contact_phone text default '',
  contact_email text default '',
  whatsapp_support text default '',
  updated_at timestamptz not null default now()
);

create table public.payments (
  id bigint generated by default as identity primary key,
  church_id bigint not null references public.churches(id) on delete restrict,
  submitted_by uuid references auth.users(id) on delete set null,
  usd_amount numeric(14, 2) not null default 0 check (usd_amount >= 0),
  bs_amount numeric(14, 2) not null default 0 check (bs_amount >= 0),
  reference text not null,
  method text not null default 'Pago Móvil',
  concept text not null default 'Aporte Mensual',
  receipt_path text,
  status public.payment_status not null default 'Pendiente',
  notes text not null default '',
  account_destination text not null default '',
  reviewed_by uuid references auth.users(id) on delete set null,
  reviewed_at timestamptz,
  created_at timestamptz not null default now(),
  unique (church_id, reference)
);

create table public.legal_requests (
  id bigint generated by default as identity primary key,
  church_id bigint not null references public.churches(id) on delete restrict,
  submitted_by uuid references auth.users(id) on delete set null,
  title text not null,
  category text not null default 'General',
  description text not null default '',
  lawyer text not null default 'Pendiente de asignación',
  status public.legal_status not null default 'Recibido',
  priority text not null default 'Media' check (priority in ('Alta', 'Media', 'Normal')),
  notes text not null default '',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index payments_church_id_idx on public.payments(church_id);
create index payments_status_idx on public.payments(status);
create index legal_requests_church_id_idx on public.legal_requests(church_id);
create index legal_requests_status_idx on public.legal_requests(status);

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create trigger churches_updated_at before update on public.churches
for each row execute function public.set_updated_at();
create trigger legal_requests_updated_at before update on public.legal_requests
for each row execute function public.set_updated_at();

create or replace function public.current_role()
returns public.user_role
language sql
stable
security definer
set search_path = public
as $$
  select role from public.profiles where id = auth.uid();
$$;

create or replace function public.current_church_id()
returns bigint
language sql
stable
security definer
set search_path = public
as $$
  select church_id from public.profiles where id = auth.uid();
$$;

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.profiles (id, name, role, church_id)
  values (
    new.id,
    coalesce(new.raw_user_meta_data ->> 'name', new.email, ''),
    coalesce((new.raw_user_meta_data ->> 'role')::public.user_role, 'church'),
    nullif(new.raw_user_meta_data ->> 'church_id', '')::bigint
  );
  return new;
end;
$$;

create trigger on_auth_user_created
  after insert on auth.users
  for each row execute function public.handle_new_user();

alter table public.churches enable row level security;
alter table public.profiles enable row level security;
alter table public.app_config enable row level security;
alter table public.payments enable row level security;
alter table public.legal_requests enable row level security;

create policy "admins manage churches" on public.churches for all to authenticated
using (public.current_role() = 'admin') with check (public.current_role() = 'admin');
create policy "church users read own church" on public.churches for select to authenticated
using (public.current_role() = 'church' and id = public.current_church_id());

create policy "users read own profile" on public.profiles for select to authenticated
using (id = auth.uid() or public.current_role() = 'admin');
create policy "admins manage profiles" on public.profiles for all to authenticated
using (public.current_role() = 'admin') with check (public.current_role() = 'admin');

create policy "authenticated read config" on public.app_config for select to authenticated
using (true);
create policy "admins manage config" on public.app_config for all to authenticated
using (public.current_role() = 'admin') with check (public.current_role() = 'admin');

create policy "admins manage payments" on public.payments for all to authenticated
using (public.current_role() = 'admin') with check (public.current_role() = 'admin');
create policy "church users read own payments" on public.payments for select to authenticated
using (public.current_role() = 'church' and church_id = public.current_church_id());
create policy "church users create own payments" on public.payments for insert to authenticated
with check (public.current_role() = 'church' and church_id = public.current_church_id() and submitted_by = auth.uid());

create policy "admins manage legal requests" on public.legal_requests for all to authenticated
using (public.current_role() = 'admin') with check (public.current_role() = 'admin');
create policy "church users read own requests" on public.legal_requests for select to authenticated
using (public.current_role() = 'church' and church_id = public.current_church_id());
create policy "church users create own requests" on public.legal_requests for insert to authenticated
with check (public.current_role() = 'church' and church_id = public.current_church_id() and submitted_by = auth.uid());

insert into public.app_config (id, bcv_rate, contact_phone, contact_email, whatsapp_support)
values (true, 45.50, '+58 212 555-0199', 'legal@cofraternidadiglesias.org', '+58 414 123-4567')
on conflict (id) do nothing;

insert into public.churches (id, name, pastor, rif, phone, email, city, address, members, status, initials, foundation_year)
overriding system value values
  (1, 'Iglesia El Buen Pastor', 'Pastor Carlos Mendoza', 'J-30491823-1', '+58 414 123-4567', 'elbuenpastor@gmail.com', 'Caracas, Dto. Capital', 'Av. Principal de Los Ruices, Edif. Esperanza Central', 180, 'Solvente', 'EB', 2012),
  (2, 'Comunidad Vida Nueva', 'Pastora Elena Gómez', 'J-40192834-2', '+58 424 987-6543', 'vidanueva.val@gmail.com', 'Valencia, Carabobo', 'Urb. El Viñedo, Calle 139, Local 4', 95, 'Solvente', 'VN', 2018),
  (3, 'Centro Cristiano La Roca', 'Pastor David Rivas', 'J-50123984-0', '+58 412 555-7890', 'laroca.lara@gmail.com', 'Barquisimeto, Lara', 'Carrera 19 con Calle 30, Galpón Alianza', 320, 'En mora', 'LR', 2008),
  (4, 'Iglesia Familiar de Gracia', 'Pastor Miguel Ángel Torres', 'J-31849201-5', '+58 416 333-2211', 'familiardegracia@gmail.com', 'Maracaibo, Zulia', 'Sector 5 de Julio con Av. Bella Vista', 140, 'Solvente', 'IF', 2015),
  (5, 'Tabernáculo de Avivamiento', 'Pastor José Luis Vargas', 'J-41029384-7', '+58 414 777-8899', 'avivamientotachira@gmail.com', 'San Cristóbal, Táchira', 'Barrio Obrero, Carrera 21 entre Calles 11 y 12', 210, 'En proceso', 'TA', 2020)
on conflict (id) do nothing;

insert into public.payments (id, church_id, usd_amount, bs_amount, reference, method, concept, status, notes, account_destination)
overriding system value values
  (1, 1, 1250.00, 56875.00, 'PAGO-839204', 'Pago Móvil (Banesco)', 'Aporte Mensual Sedes (Enero - Marzo)', 'Pendiente', 'Requiere verificación de la cuenta recaudadora', 'Banesco · Cta. Corriente *9102'),
  (2, 2, 250.00, 11375.00, 'PAGO-839188', 'Transferencia (Mercantil)', 'Aporte Mensual Febrero', 'Pendiente', 'Transferencia del mismo banco confirmada por tesorería', 'Mercantil · Cta. Corriente *4581'),
  (3, 3, 750.00, 34125.00, 'PAGO-838901', 'Zelle', 'Arancel Trámite Título Supletorio', 'Pendiente', 'Referencia Zelle: David Rivas (Tesorería)', 'Zelle · finanzas@cofraternidad.org'),
  (4, 4, 180.00, 8190.00, 'PAGO-838774', 'Pago Móvil (Bancamiga)', 'Aporte Mensual Febrero', 'Aprobado', 'Validado conforme en cuenta bancaria', 'Bancamiga · Pago Móvil')
on conflict (id) do nothing;

insert into public.legal_requests (id, church_id, title, category, description, lawyer, status, priority, notes)
overriding system value values
  (1, 3, 'Título Supletorio de Templo Central', 'Inmuebles y Terrenos', 'Solicitud de acreditación posesoria y título supletorio para el terreno y edificación del templo principal.', 'Dra. Mariela Ramos', 'En Notaría/Registro', 'Alta', 'Documento en despacho de Notaría Primera.'),
  (2, 5, 'Actualización de Junta Directiva y Estatutos', 'Constitución Legal', 'Inscripción del acta de asamblea extraordinaria para actualización de directivos.', 'Dr. Alejandro Peña', 'En análisis', 'Media', 'Revisión del libro de actas.'),
  (3, 1, 'Solvencia Eclesiástica Anual', 'Solvencia', 'Constancia oficial de afiliación activa y solvencia institucional.', 'Dra. Mariela Ramos', 'Concluido', 'Normal', 'Documento entregado al pastor.')
on conflict (id) do nothing;

select setval(pg_get_serial_sequence('public.churches', 'id'), coalesce((select max(id) from public.churches), 1));
select setval(pg_get_serial_sequence('public.payments', 'id'), coalesce((select max(id) from public.payments), 1));
select setval(pg_get_serial_sequence('public.legal_requests', 'id'), coalesce((select max(id) from public.legal_requests), 1));

insert into storage.buckets (id, name, public)
values ('payment-receipts', 'payment-receipts', false)
on conflict (id) do nothing;

create policy "church users upload own receipts" on storage.objects for insert to authenticated
with check (bucket_id = 'payment-receipts' and (storage.foldername(name))[1] = public.current_church_id()::text);
create policy "authenticated read receipts" on storage.objects for select to authenticated
using (bucket_id = 'payment-receipts' and (public.current_role() = 'admin' or (storage.foldername(name))[1] = public.current_church_id()::text));